/-
  CompactSU3_v3.lean

  Exact scope
  -----------
  This file formalises the Gaussian-integer lattice inside su(3):

    {A : M_3(Z[i]) | A^dagger = -A and trace A = 0}  <->  Z^8.

  It deliberately does not rename this lattice as the continuous real Lie
  algebra su(3), and it does not claim to construct the Lie group SU(3) or QCD.
  Its new ODE section formalises the algebraic coefficient vector field
  generated by [D,-].  Passing from that vector field to a continuous ODE
  requires scalar extension from Z to R in a Mathlib companion file.

  Audit notes added on integration into the main project
  ------------------------------------------------------
  * Two compilation blockers were fixed on import.  (a) The docstring below
    wrote plus-or-minus as the three characters plus, slash, minus.  Lean block
    comments *nest*, so each such sequence opened a comment that was never
    closed, and everything after it was eaten.  (Writing this note, the same
    mistake was made a second time — the sequence has to be avoided entirely,
    or written as the single character shown here: ±.)
    (b) `coeffEquivSu3Lattice` used `Equiv` (`≃`), which is Mathlib, not Std;
    it is now stated as an explicit two-sided inverse, `coeff_lattice_bijection`.
  * The eight coefficient equations of `Coeff8.adD` were re-derived
    independently by symbolic computation over `ℂ` and agree term by term.
    `[Dg, X]` was separately confirmed to stay anti-Hermitian and traceless.
  * `Dg` was confirmed equal to `Core.D` as a real matrix, and
    `Dg * Dg = -3 I + J` reproduces `Core.D_squared`.
  * No `sorry`, no `native_decide`, no new `axiom`.

  What is *not* established here
  ------------------------------
  The carrier is the ℤ[i]-points of su(3): a rank-8 Lie **ring**, closed under
  bracket.  That its ℝ-span is the compact real Lie algebra su(3) is not stated
  and cannot be, since there are no reals in this file.  Likewise `adD` is an
  integer-coefficient vector field, not an ODE; `dX/dt = [D,X]` needs ℝ.
-/

import CubeToSU3.Core

namespace CubeToSU3

/-- Gaussian integer. -/
structure GInt where
  re : Int
  im : Int
deriving Repr, DecidableEq

namespace GInt
def zero : GInt := ⟨0, 0⟩
def one  : GInt := ⟨1, 0⟩
def i    : GInt := ⟨0, 1⟩
def add (a b : GInt) : GInt := ⟨a.re + b.re, a.im + b.im⟩
def neg (a : GInt) : GInt := ⟨-a.re, -a.im⟩
def sub (a b : GInt) : GInt := add a (neg b)
def mul (a b : GInt) : GInt := ⟨a.re*b.re - a.im*b.im, a.re*b.im + a.im*b.re⟩
def conj (a : GInt) : GInt := ⟨a.re, -a.im⟩
end GInt

/-- 3x3 matrix over the Gaussian integers. -/
structure MatG3 where
  a00 : GInt
  a01 : GInt
  a02 : GInt
  a10 : GInt
  a11 : GInt
  a12 : GInt
  a20 : GInt
  a21 : GInt
  a22 : GInt
deriving Repr, DecidableEq

namespace MatG3
open GInt

def neg (A : MatG3) : MatG3 :=
  ⟨GInt.neg A.a00, GInt.neg A.a01, GInt.neg A.a02,
   GInt.neg A.a10, GInt.neg A.a11, GInt.neg A.a12,
   GInt.neg A.a20, GInt.neg A.a21, GInt.neg A.a22⟩

def sub (A B : MatG3) : MatG3 :=
  ⟨GInt.sub A.a00 B.a00, GInt.sub A.a01 B.a01, GInt.sub A.a02 B.a02,
   GInt.sub A.a10 B.a10, GInt.sub A.a11 B.a11, GInt.sub A.a12 B.a12,
   GInt.sub A.a20 B.a20, GInt.sub A.a21 B.a21, GInt.sub A.a22 B.a22⟩

def mul (A B : MatG3) : MatG3 :=
  ⟨GInt.add (GInt.add (GInt.mul A.a00 B.a00) (GInt.mul A.a01 B.a10)) (GInt.mul A.a02 B.a20),
   GInt.add (GInt.add (GInt.mul A.a00 B.a01) (GInt.mul A.a01 B.a11)) (GInt.mul A.a02 B.a21),
   GInt.add (GInt.add (GInt.mul A.a00 B.a02) (GInt.mul A.a01 B.a12)) (GInt.mul A.a02 B.a22),
   GInt.add (GInt.add (GInt.mul A.a10 B.a00) (GInt.mul A.a11 B.a10)) (GInt.mul A.a12 B.a20),
   GInt.add (GInt.add (GInt.mul A.a10 B.a01) (GInt.mul A.a11 B.a11)) (GInt.mul A.a12 B.a21),
   GInt.add (GInt.add (GInt.mul A.a10 B.a02) (GInt.mul A.a11 B.a12)) (GInt.mul A.a12 B.a22),
   GInt.add (GInt.add (GInt.mul A.a20 B.a00) (GInt.mul A.a21 B.a10)) (GInt.mul A.a22 B.a20),
   GInt.add (GInt.add (GInt.mul A.a20 B.a01) (GInt.mul A.a21 B.a11)) (GInt.mul A.a22 B.a21),
   GInt.add (GInt.add (GInt.mul A.a20 B.a02) (GInt.mul A.a21 B.a12)) (GInt.mul A.a22 B.a22)⟩

def trace (A : MatG3) : GInt := GInt.add (GInt.add A.a00 A.a11) A.a22

def conjTranspose (A : MatG3) : MatG3 :=
  ⟨GInt.conj A.a00, GInt.conj A.a10, GInt.conj A.a20,
   GInt.conj A.a01, GInt.conj A.a11, GInt.conj A.a21,
   GInt.conj A.a02, GInt.conj A.a12, GInt.conj A.a22⟩

def transpose (A : MatG3) : MatG3 :=
  ⟨A.a00, A.a10, A.a20, A.a01, A.a11, A.a21, A.a02, A.a12, A.a22⟩

def mulI (A : MatG3) : MatG3 :=
  ⟨GInt.mul GInt.i A.a00, GInt.mul GInt.i A.a01, GInt.mul GInt.i A.a02,
   GInt.mul GInt.i A.a10, GInt.mul GInt.i A.a11, GInt.mul GInt.i A.a12,
   GInt.mul GInt.i A.a20, GInt.mul GInt.i A.a21, GInt.mul GInt.i A.a22⟩

def bracket (A B : MatG3) : MatG3 := sub (mul A B) (mul B A)

def zero : MatG3 :=
  ⟨GInt.zero, GInt.zero, GInt.zero, GInt.zero, GInt.zero,
   GInt.zero, GInt.zero, GInt.zero, GInt.zero⟩

end MatG3

/-- Membership in the Gaussian-integer lattice inside `su(3)`.
    This is an integral lattice predicate, not the full real Lie algebra. -/
def IsSu3Alg (A : MatG3) : Prop :=
  MatG3.conjTranspose A = MatG3.neg A ∧ MatG3.trace A = GInt.zero

/-- The precise carrier proved equivalent to eight integer coordinates below. -/
def Su3Lattice := {A : MatG3 // IsSu3Alg A}

/-- The eight real coefficients repackaged. -/
def compactMatrix (p q u12 v12 u13 v13 u23 v23 : Int) : MatG3 :=
  ⟨⟨0, p⟩,        ⟨u12, v12⟩,   ⟨u13, v13⟩,
   ⟨-u12, v12⟩,   ⟨0, -p + q⟩,  ⟨u23, v23⟩,
   ⟨-u13, v13⟩,   ⟨-u23, v23⟩,  ⟨0, -q⟩⟩

theorem compactMatrix_mem_su3 (p q u12 v12 u13 v13 u23 v23 : Int) :
    IsSu3Alg (compactMatrix p q u12 v12 u13 v13 u23 v23) := by
  constructor <;>
    simp [IsSu3Alg, compactMatrix, MatG3.conjTranspose, MatG3.neg, MatG3.trace,
          GInt.conj, GInt.neg, GInt.add, GInt.zero, MatG3.mk.injEq, GInt.mk.injEq] <;>
    omega

/-! ## Injectivity: the eight coordinates survive -/

theorem compactMatrix_injective
    {p q u12 v12 u13 v13 u23 v23 p' q' u12' v12' u13' v13' u23' v23' : Int}
    (h : compactMatrix p q u12 v12 u13 v13 u23 v23 =
         compactMatrix p' q' u12' v12' u13' v13' u23' v23') :
    p = p' ∧ q = q' ∧ u12 = u12' ∧ v12 = v12' ∧
    u13 = u13' ∧ v13 = v13' ∧ u23 = u23' ∧ v23 = v23' := by
  simp [compactMatrix, MatG3.mk.injEq, GInt.mk.injEq] at h
  omega

/-! ## Surjectivity: every element of su(3) is reached -/

theorem compactMatrix_surjective {A : MatG3} (hA : IsSu3Alg A) :
    A = compactMatrix A.a00.im (-A.a22.im) A.a01.re A.a01.im
          A.a02.re A.a02.im A.a12.re A.a12.im := by
  obtain ⟨h1, h2⟩ := hA
  obtain ⟨⟨r00,i00⟩,⟨r01,i01⟩,⟨r02,i02⟩,⟨r10,i10⟩,⟨r11,i11⟩,
          ⟨r12,i12⟩,⟨r20,i20⟩,⟨r21,i21⟩,⟨r22,i22⟩⟩ := A
  simp [MatG3.conjTranspose, MatG3.neg, MatG3.trace, GInt.conj, GInt.neg,
        GInt.add, GInt.zero, MatG3.mk.injEq, GInt.mk.injEq] at h1 h2
  simp [compactMatrix, MatG3.mk.injEq, GInt.mk.injEq]
  omega

theorem exists_coords {A : MatG3} (hA : IsSu3Alg A) :
    ∃ p q u12 v12 u13 v13 u23 v23 : Int,
      A = compactMatrix p q u12 v12 u13 v13 u23 v23 :=
  ⟨_, _, _, _, _, _, _, _, compactMatrix_surjective hA⟩

/-! ## Package the eight coordinates and the lattice equivalence -/

/-- Two diagonal real coordinates and three complex pairs: `2 + 3*2 = 8`. -/
structure Coeff8 where
  p   : Int
  q   : Int
  u12 : Int
  v12 : Int
  u13 : Int
  v13 : Int
  u23 : Int
  v23 : Int
deriving Repr, DecidableEq

namespace Coeff8

def toMatrix (c : Coeff8) : MatG3 :=
  compactMatrix c.p c.q c.u12 c.v12 c.u13 c.v13 c.u23 c.v23

def ofMatrix (A : MatG3) : Coeff8 :=
  ⟨A.a00.im, -A.a22.im,
   A.a01.re, A.a01.im, A.a02.re, A.a02.im, A.a12.re, A.a12.im⟩

theorem toMatrix_mem (c : Coeff8) : IsSu3Alg c.toMatrix :=
  compactMatrix_mem_su3 _ _ _ _ _ _ _ _

theorem ofMatrix_toMatrix (c : Coeff8) : ofMatrix c.toMatrix = c := by
  cases c
  simp [ofMatrix, toMatrix, compactMatrix, Coeff8.mk.injEq]

theorem toMatrix_ofMatrix {A : MatG3} (hA : IsSu3Alg A) :
    (ofMatrix A).toMatrix = A := by
  simpa [ofMatrix, toMatrix] using (compactMatrix_surjective hA).symm

end Coeff8

/-- Machine-level packaging of the exact result proved here: eight integers are
    in bijection with the Gaussian-integer `su(3)` lattice.

    Stated as an explicit two-sided inverse rather than with `Equiv` (`≃`),
    which lives in Mathlib and would break this file's Std-only claim. -/
theorem coeff_lattice_bijection :
    (∀ c : Coeff8, Coeff8.ofMatrix c.toMatrix = c) ∧
    (∀ A : MatG3, IsSu3Alg A → (Coeff8.ofMatrix A).toMatrix = A) :=
  ⟨Coeff8.ofMatrix_toMatrix, fun _ hA => Coeff8.toMatrix_ofMatrix hA⟩

namespace MatG3
def add (A B : MatG3) : MatG3 :=
  ⟨GInt.add A.a00 B.a00, GInt.add A.a01 B.a01, GInt.add A.a02 B.a02,
   GInt.add A.a10 B.a10, GInt.add A.a11 B.a11, GInt.add A.a12 B.a12,
   GInt.add A.a20 B.a20, GInt.add A.a21 B.a21, GInt.add A.a22 B.a22⟩

def smulInt (n : Int) (A : MatG3) : MatG3 :=
  ⟨GInt.mul ⟨n,0⟩ A.a00, GInt.mul ⟨n,0⟩ A.a01, GInt.mul ⟨n,0⟩ A.a02,
   GInt.mul ⟨n,0⟩ A.a10, GInt.mul ⟨n,0⟩ A.a11, GInt.mul ⟨n,0⟩ A.a12,
   GInt.mul ⟨n,0⟩ A.a20, GInt.mul ⟨n,0⟩ A.a21, GInt.mul ⟨n,0⟩ A.a22⟩

def idM : MatG3 :=
  ⟨GInt.one, GInt.zero, GInt.zero,
   GInt.zero, GInt.one, GInt.zero,
   GInt.zero, GInt.zero, GInt.one⟩

def J : MatG3 :=
  ⟨GInt.one, GInt.one, GInt.one,
   GInt.one, GInt.one, GInt.one,
   GInt.one, GInt.one, GInt.one⟩
end MatG3

/-! ## The eight basis directions -/

def K12 : MatG3 := compactMatrix 0 0 1 0 0 0 0 0
def L12 : MatG3 := compactMatrix 0 0 0 1 0 0 0 0
def K13 : MatG3 := compactMatrix 0 0 0 0 1 0 0 0
def L13 : MatG3 := compactMatrix 0 0 0 0 0 1 0 0
def K23 : MatG3 := compactMatrix 0 0 0 0 0 0 1 0
def L23 : MatG3 := compactMatrix 0 0 0 0 0 0 0 1
def C1  : MatG3 := compactMatrix 1 0 0 0 0 0 0 0
def C2  : MatG3 := compactMatrix 0 1 0 0 0 0 0 0

theorem K12_mem : IsSu3Alg K12 := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem L12_mem : IsSu3Alg L12 := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem K13_mem : IsSu3Alg K13 := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem L13_mem : IsSu3Alg L13 := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem K23_mem : IsSu3Alg K23 := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem L23_mem : IsSu3Alg L23 := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem C1_mem  : IsSu3Alg C1  := compactMatrix_mem_su3 _ _ _ _ _ _ _ _
theorem C2_mem  : IsSu3Alg C2  := compactMatrix_mem_su3 _ _ _ _ _ _ _ _

/-- Path 1<->2 composed with 2<->3 gives 1<->3. -/
theorem bracket_K12_K23 : MatG3.bracket K12 K23 = K13 := by decide

/-- Two orthogonal 1<->2 directions produce the first Cartan direction. -/
theorem bracket_K12_L12 : MatG3.bracket K12 L12 = MatG3.smulInt 2 C1 := by decide

/-! ## phi is not a Lie algebra homomorphism -/

/-- Two real symmetric directions (the part that must be multiplied by i). -/
def S12g : MatG3 :=
  ⟨GInt.zero, GInt.one, GInt.zero,
   GInt.one, GInt.zero, GInt.zero,
   GInt.zero, GInt.zero, GInt.zero⟩

def S13g : MatG3 :=
  ⟨GInt.zero, GInt.zero, GInt.one,
   GInt.zero, GInt.zero, GInt.zero,
   GInt.one, GInt.zero, GInt.zero⟩

/-- Any coefficient-transfer map of Weyl unitary-trick shape. -/
def PhiSpec (f : MatG3 → MatG3) : Prop :=
  (∀ A, MatG3.transpose A = MatG3.neg A → f A = A) ∧
  (∀ A, MatG3.transpose A = A → f A = MatG3.mulI A)

theorem bracket_S12_S13 : MatG3.bracket S12g S13g = K23 := by decide

theorem bracket_mulI_S12_S13 :
    MatG3.bracket (MatG3.mulI S12g) (MatG3.mulI S13g) = MatG3.neg K23 := by decide

/-- MAIN NEGATIVE RESULT: no map with the Weyl-trick shape preserves brackets. -/
theorem no_phi_is_lie_hom (f : MatG3 → MatG3) (hf : PhiSpec f)
    (hhom : ∀ A B, f (MatG3.bracket A B) = MatG3.bracket (f A) (f B)) : False := by
  have hS12 : f S12g = MatG3.mulI S12g := hf.2 S12g (by decide)
  have hS13 : f S13g = MatG3.mulI S13g := hf.2 S13g (by decide)
  have hK   : f K23  = K23             := hf.1 K23  (by decide)
  have h := hhom S12g S13g
  rw [bracket_S12_S13, hK, hS12, hS13, bracket_mulI_S12_S13] at h
  exact absurd h (by decide)

/-! ## The v10.1 cyclic difference D -/

def Dg : MatG3 := compactMatrix 0 0 1 0 (-1) 0 1 0

theorem Dg_mem : IsSu3Alg Dg := compactMatrix_mem_su3 _ _ _ _ _ _ _ _

theorem Dg_decomposition : Dg = MatG3.add (MatG3.sub K12 K13) K23 := by decide

/-- The integer identity survives complexification verbatim. -/
theorem Dg_squared : MatG3.mul Dg Dg = MatG3.add (MatG3.smulInt (-3) MatG3.idM) MatG3.J := by
  decide

/-- D is real antisymmetric, so every Weyl-trick map fixes it:
    D lies in the three-dimensional intersection and constrains no real form. -/
theorem Dg_antisymm : MatG3.transpose Dg = MatG3.neg Dg := by decide

theorem phi_fixes_Dg (f : MatG3 → MatG3) (hf : PhiSpec f) : f Dg = Dg :=
  hf.1 Dg Dg_antisymm

/-! ## The coefficient vector field generated by D

    The matrix equation is the algebraic core of the naive Lax ODE

      dX/dt = [D,X].

    Since this Std-only file has integer scalars, it proves the vector-field
    identity exactly but does not pretend that derivatives over `Int` exist.
    After scalar extension to `Real`, the same formula becomes the continuous
    eight-component ODE. -/

namespace Coeff8

/-- The eight coefficient equations obtained by expanding `[D,X]` in the
    compact basis.  All coefficients are 0, ±1 or ±2, coming from the bracket:

      p'   =  2(v12-v13)             q'   = 2(v23-v13)
      u12' =  u13+u23                v12' = -2p+q+v13-v23
      u13' = -u12+u23                v13' = p+q-v12+v23
      u23' = -u12-u13                v23' = p-2q+v12-v13

    An overall continuous scale `kappa` is intentionally not inserted over
    `Int`; after scalar extension to `Real`, multiply this whole RHS by it. -/
def adD (c : Coeff8) : Coeff8 :=
  ⟨2 * (c.v12 - c.v13),
   2 * (c.v23 - c.v13),
   c.u13 + c.u23,
   -2 * c.p + c.q + c.v13 - c.v23,
   -c.u12 + c.u23,
   c.p + c.q - c.v12 + c.v23,
   -c.u12 - c.u13,
   c.p - 2 * c.q + c.v12 - c.v13⟩

/-- The three genuine complex off-diagonal coordinates. -/
def z12 (c : Coeff8) : GInt := ⟨c.u12, c.v12⟩
def z13 (c : Coeff8) : GInt := ⟨c.u13, c.v13⟩
def z23 (c : Coeff8) : GInt := ⟨c.u23, c.v23⟩

end Coeff8

/-- Central algebraic identity behind the naive ODE:
    applying the commutator with `Dg` is exactly the displayed eight-equation
    coefficient vector field `Coeff8.adD`. -/
theorem bracket_Dg_coefficients (c : Coeff8) :
    MatG3.bracket Dg c.toMatrix = (Coeff8.adD c).toMatrix := by
  rcases c with ⟨p, q, u12, v12, u13, v13, u23, v23⟩
  simp [Coeff8.toMatrix, Coeff8.adD, Dg, compactMatrix,
        MatG3.bracket, MatG3.mul, MatG3.sub,
        GInt.add, GInt.sub, GInt.neg, GInt.mul,
        MatG3.mk.injEq, GInt.mk.injEq]
  omega

/-- Consequently the `D`-generated vector field stays in the integral lattice. -/
theorem bracket_Dg_mem (c : Coeff8) :
    IsSu3Alg (MatG3.bracket Dg c.toMatrix) := by
  rw [bracket_Dg_coefficients]
  exact Coeff8.toMatrix_mem _

/-! The same equations written as three complex equations.

    z12' = z13 + conj(z23) + i*(-2p+q)
    z13' = -z12 + z23       + i*( p+q)
    z23' = -conj(z12)-z13   + i*( p-2q)
-/

theorem adD_z12 (c : Coeff8) :
    (Coeff8.adD c).z12 =
      GInt.add (GInt.add c.z13 (GInt.conj c.z23))
        (GInt.mul GInt.i ⟨-2 * c.p + c.q, 0⟩) := by
  cases c
  simp [Coeff8.adD, Coeff8.z12, Coeff8.z13, Coeff8.z23,
        GInt.add, GInt.conj, GInt.mul, GInt.i, GInt.mk.injEq]
  omega

theorem adD_z13 (c : Coeff8) :
    (Coeff8.adD c).z13 =
      GInt.add (GInt.sub c.z23 c.z12)
        (GInt.mul GInt.i ⟨c.p + c.q, 0⟩) := by
  cases c
  simp [Coeff8.adD, Coeff8.z12, Coeff8.z13, Coeff8.z23,
        GInt.add, GInt.sub, GInt.neg, GInt.mul, GInt.i, GInt.mk.injEq]
  omega

theorem adD_z23 (c : Coeff8) :
    (Coeff8.adD c).z23 =
      GInt.add (GInt.neg (GInt.add (GInt.conj c.z12) c.z13))
        (GInt.mul GInt.i ⟨c.p - 2 * c.q, 0⟩) := by
  cases c
  simp [Coeff8.adD, Coeff8.z12, Coeff8.z13, Coeff8.z23,
        GInt.add, GInt.neg, GInt.conj, GInt.mul, GInt.i, GInt.mk.injEq]
  omega

/-- Embed the v10.1 integer matrices into the Gaussian-integer ones. -/
def ofMat3 (A : Mat3) : MatG3 :=
  ⟨⟨A.a00,0⟩, ⟨A.a01,0⟩, ⟨A.a02,0⟩,
   ⟨A.a10,0⟩, ⟨A.a11,0⟩, ⟨A.a12,0⟩,
   ⟨A.a20,0⟩, ⟨A.a21,0⟩, ⟨A.a22,0⟩⟩

/-- BRIDGE: the su(3) element Dg is literally the image of the v10.1 core's D.
    No digit of the original integer matrix is changed. -/
theorem Dg_eq_image_of_core_D : Dg = ofMat3 D := by decide



/-! ## Axiom audit -/

#print axioms compactMatrix_mem_su3
#print axioms compactMatrix_injective
#print axioms compactMatrix_surjective
#print axioms Coeff8.ofMatrix_toMatrix
#print axioms bracket_K12_K23
#print axioms no_phi_is_lie_hom
#print axioms Dg_squared
#print axioms bracket_Dg_coefficients
#print axioms bracket_Dg_mem
#print axioms adD_z12
#print axioms adD_z13
#print axioms adD_z23
#print axioms Dg_eq_image_of_core_D

end CubeToSU3
