import CubeToSU3.LatticeNonFlat

/-!
# 連結變數的取值來自纖維側的 `D`

`LatticeNonFlat` wrote down the link variable `Prot` (the 120° rotation about the
乾-坤 diagonal) as an explicit matrix, and `WilsonAction` computed its Wilson
action.  This file connects that matrix back to the generator `D = P - P²` that
the `Cube → su(3) → SU(3)` line is built from.

**角色須知(承 `WilsonAction` 的提醒)。**  底空間的立方體與纖維側的立方體是兩
個不能互換的角色,這裡沒有把它們接在一起。連結變數的*取值*本來就住在規範群
`SU(3)` 裡,也就是纖維側;本檔案證的只是「這個取值等於纖維側 `D` 的指數」,不
是「底空間的頂點就是色方向」。

**What is proved here (pure matrix algebra, no analysis).**

* `DmatM = PmatM - PmatM * PmatM` is anti-Hermitian and traceless, hence a
  candidate element of `su(3)`.
* `D² = -3·1 + J`   (`J` = all-ones), the identity already known from `Cube.lean`
  in the integer setting, here over `ℂ`.
* `D³ = -3·D`, so the real algebra generated by `D` is `ℝ[x]/(x³+3x)`.
* `PmatM + PmatM = -1 + J + DmatM`.

The last identity is exactly the Rodrigues value of `exp (θ D)` at
`θ = 2π/(3√3)`: with `√3 θ = 2π/3`, `sin = √3/2` and `cos = -1/2`,

    exp (θ D) = 1 + (sin(√3θ)/√3) D + ((1-cos(√3θ))/3) D²
              = 1 + (1/2) D + (1/2)(-3·1 + J)
              = (-1 + J + D)/2
              = PmatM.

The analytic step (`Matrix.exp (θ • D) = PmatM`) is left to a later file; it
needs either Rodrigues' formula for a 3×3 antisymmetric matrix, or the Fourier
diagonalisation `D = U · diag(0, i√3, -i√3) · Uᴴ` together with
`Matrix.exp_conj` and `Matrix.exp_diagonal`.  Everything below is finite
algebra: statements use explicit matrix literals instead of scalar actions, so
no `SMul` instance has to be resolved.

Nothing here is a physical claim.
-/

noncomputable section

open Matrix

namespace CubeToSU3.Lattice

open CubeToSU3 CubeToSU3.Continuous

/-- The all-ones matrix. -/
def JmatM : M3C := !![1, 1, 1; 1, 1, 1; 1, 1, 1]

/-- The fibre-side generator `D = P - P²`, over `ℂ`. -/
def DmatM : M3C := PmatM - PmatM * PmatM

/-- `D` written out. -/
theorem DmatM_eq : DmatM = !![0, -1, 1; 1, 0, -1; -1, 1, 0] := by
  unfold DmatM
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [PmatM, Matrix.sub_apply, Matrix.mul_apply, Fin.sum_univ_three] <;> norm_num

/-- `D` is anti-Hermitian: a candidate element of `su(3)`. -/
theorem DmatM_antiHermitian : DmatMᴴ = -DmatM := by
  rw [DmatM_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.conjTranspose_apply, Matrix.neg_apply] <;> norm_num

/-- `D` is traceless. -/
theorem DmatM_trace : Matrix.trace DmatM = 0 := by
  rw [DmatM_eq]
  simp [Matrix.trace_fin_three]

/-- `D²`, written out. -/
theorem DmatM_sq_eq : DmatM * DmatM = !![-2, 1, 1; 1, -2, 1; 1, 1, -2] := by
  rw [DmatM_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_three] <;> norm_num

/-- The right-hand side above is `-3·1 + J`, so the previous theorem reads
    `D² = -3·1 + J`.  The `3` is `|(1,1,1)|²`, the source of every `√3` in the
    project. -/
theorem neg_three_one_add_J :
    (-!![(3 : ℂ), 0, 0; 0, 3, 0; 0, 0, 3]) + JmatM
      = !![-2, 1, 1; 1, -2, 1; 1, 1, -2] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [JmatM, Matrix.add_apply, Matrix.neg_apply] <;> norm_num

/-- `D³`, written out. -/
theorem DmatM_cube_eq :
    DmatM * DmatM * DmatM = !![0, 3, -3; -3, 0, 3; 3, -3, 0] := by
  rw [DmatM_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_three] <;> norm_num

/-- The right-hand side above is `-3·D`, so `D³ = -3·D`: the minimal polynomial
    of `D` is `x³ + 3x`. -/
theorem neg_three_DmatM :
    -(DmatM + DmatM + DmatM) = !![0, 3, -3; -3, 0, 3; 3, -3, 0] := by
  rw [DmatM_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.add_apply, Matrix.neg_apply] <;> norm_num

/-- **The bridge.**  The link variable used by `WilsonAction` is the Rodrigues
    value of `exp (θ D)` at `θ = 2π/(3√3)`, stated without any analysis:

      `Prot + Prot = -1 + J + D`.

    So the connection whose Wilson action is `32` takes its value in the
    one-parameter subgroup generated by the fibre-side `D`. -/
theorem PmatM_add_PmatM :
    PmatM + PmatM
      = (-!![(1 : ℂ), 0, 0; 0, 1, 0; 0, 0, 1]) + JmatM + DmatM := by
  rw [DmatM_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [PmatM, JmatM, Matrix.add_apply, Matrix.neg_apply] <;> norm_num

/-! ## Axiom audit -/

#print axioms DmatM_eq
#print axioms DmatM_antiHermitian
#print axioms DmatM_trace
#print axioms DmatM_sq_eq
#print axioms neg_three_one_add_J
#print axioms DmatM_cube_eq
#print axioms neg_three_DmatM
#print axioms PmatM_add_PmatM

end CubeToSU3.Lattice
